# Generated by Django 4.2.16 on 2025-09-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="End date for multi-date events", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Date Event"),
                    ("recurring", "Recurring Event"),
                    ("span", "Multi-Date Span Event"),
                ],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(
                help_text="Start date for single events, or first date for multi-date events"
            ),
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("session_number", models.PositiveIntegerField(default=1)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=300)),
                ("qr_code", models.CharField(blank=True, max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "ordering": ["session_date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["session_date", "is_active"],
                        name="events_even_session_63077b_idx",
                    ),
                    models.Index(
                        fields=["qr_code"], name="events_even_qr_code_5ee374_idx"
                    ),
                ],
                "unique_together": {("event", "session_date")},
            },
        ),
    ]
