# Production configuration for Docker Compose
# Use this file for production deployment: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  web:
    environment:
      - DEBUG=False
      - SECURE_SSL_REDIRECT=True
      - SECURE_HSTS_SECONDS=31536000
      - SECURE_HSTS_INCLUDE_SUBDOMAINS=True
      - SECURE_HSTS_PRELOAD=True
      - SECURE_CONTENT_TYPE_NOSNIFF=True
      - SECURE_BROWSER_XSS_FILTER=True
      - SESSION_COOKIE_SECURE=True
      - CSRF_COOKIE_SECURE=True
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Remove port mapping for security in production
    ports: []

  redis:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Remove port mapping for security in production
    ports: []

