# Development override for Docker Compose
# This file is automatically loaded by docker-compose for local development

version: '3.8'

services:
  web:
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dev_password_123

