# Generated by Django 4.2.16 on 2025-09-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("attendees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("device_fingerprint", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendees.attendee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeviceFootprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_resolution", models.CharField(blank=True, max_length=20)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("platform", models.CharField(blank=True, max_length=50)),
                ("browser_fingerprint", models.TextField(blank=True)),
                (
                    "attendance_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.attendancerecord",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["timestamp"], name="attendance__timesta_01c0dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["event", "attendee"], name="attendance__event_i_19d3da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("event", "attendee")},
        ),
    ]
