# Generated by Django 4.2.16 on 2025-09-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attendees", "0001_initial"),
        ("events", "0002_event_end_date_event_event_type_alter_event_date_and_more"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicefootprint",
            name="attendance_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.attendancerecord",
            ),
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("device_fingerprint", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendees.attendee",
                    ),
                ),
                (
                    "event_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="devicefootprint",
            name="session_attendance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.sessionattendance",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionattendance",
            index=models.Index(
                fields=["timestamp"], name="attendance__timesta_b21f01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionattendance",
            index=models.Index(
                fields=["event_session", "attendee"],
                name="attendance__event_s_98c51d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionattendance",
            unique_together={("event_session", "attendee")},
        ),
    ]
