# Generated by Django 4.2.16 on 2025-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_attendancecheckpoint_checkpointattendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecheckpoint",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("all_days", "All Days"),
                    ("specific_day", "Specific Day Only"),
                    ("weekdays", "Weekdays Only"),
                    ("weekends", "Weekends Only"),
                ],
                default="all_days",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendancecheckpoint",
            name="specific_date",
            field=models.DateField(
                blank=True, help_text="For specific_day checkpoints only", null=True
            ),
        ),
    ]
