# Generated by Django 4.2.16 on 2025-09-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_attendancecheckpoint_applies_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS Latitude",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="location_accuracy",
            field=models.FloatField(
                blank=True, help_text="Location accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="location_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When location was captured", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS Longitude",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkpointattendance",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS Latitude",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkpointattendance",
            name="location_accuracy",
            field=models.FloatField(
                blank=True, help_text="Location accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="checkpointattendance",
            name="location_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When location was captured", null=True
            ),
        ),
        migrations.AddField(
            model_name="checkpointattendance",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS Longitude",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS Latitude",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="location_accuracy",
            field=models.FloatField(
                blank=True, help_text="Location accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="location_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When location was captured", null=True
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS Longitude",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["latitude", "longitude"], name="attendance__latitud_a3292a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkpointattendance",
            index=models.Index(
                fields=["latitude", "longitude"], name="attendance__latitud_c98d43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionattendance",
            index=models.Index(
                fields=["latitude", "longitude"], name="attendance__latitud_ee0c10_idx"
            ),
        ),
    ]
